# https://github.com/sproogen/modern-resume-theme
# build website: "bundle exec jekyll serve"

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: James Gardner
title: Physics Research Student
email: james.gardner@anu.edu.au
website: jamesgardner.info

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
orcid_username: 0000-0002-8592-1452
github_username: daccordeon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's James, and I'm a physics research student. I currently work at The Australian National University's Centre for Gravitational Astrophysics as part of the theoretical arm of the quantum-squeezing research group.

  My research interests include <mark>Quantum Optics</mark>, <mark>Gravitational Waves</mark>, and <mark>Quantum Squeezing</mark>. I enjoy discovering a simple understanding of physical phenomena from complex analytic models. I believe in Open Research and Open Source. My CV is available as a PDF [here](https://daccordeon.github.io/assets/James_W_Gardner_CV.pdf).

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Australian National University (ANU)
        caption: 2018 - 2021
        sub_title: Bachelor of Philosophy (Honours) in Science with First Class Honours in Physics
        description: | # this will include new lines to allow paragraphs
          During my time at ANU, I enjoyed learning through asking many fruitful questions and found good company and help from my peers.

          My First Class Honours thesis is available [here](https://daccordeon.github.io/assets/James_W_Gardner_Honours_thesis.pdf), in which I explored a novel use of squeezing to improve the sensitivity of gravitational-wave detectors (called <mark>Nondegenerate Internal Squeezing</mark>). The slides for my final Honours talk to the ANU School of Physics are available [here](https://daccordeon.github.io/assets/James_W_Gardner_Honours_final_talk_slides.pdf). 

  - title: Awards and scholarships # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - Australian Government Research Training Program Domestic Scholarship - 2022
      - ANU Supplementary Scholarship - 2022
      - ANU First Class Honours - 2021
      - ANU Achievement Prize for Third Year Physics - 2020
      - ANU Dean’s Science Education Commendation Award - 2020
      - ANU National University Scholarship - 2018–2021
                   
  - title: Publications as James W. Gardner # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - **James W. Gardner**, Hannah Middleton, Changrong Liu, Andrew Melatos, Robin Evans, William Moran, et al., Accepted December 2021, *Continuous gravitational waves in the lab: recovering audio signals with a table-top optical microphone*, American Journal of Physics.

      Papers are available upon request.

  - title: Involvement in the research community # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs       
      ## Presentations

      - LIGO-Virgo-KAGRA Collaboration Interferometer simulation group - December 2020, *Verification of the newly-added non-linear element in Finesse for optical modelling of advanced gravitational-wave detector configurations*
      - Various presentations to the ANU Centre for Gravitational Astrophysics

      Slides are available upon request.


      ## Membership
      
      - The ARC Centre of Excellence for Gravitational Wave Discovery (OzGrav, ANU Node) - 2020–present

  - title: Outside of academia # Recreation
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not working in the quantum realm, I enjoy playing games and music with friends. I love storytelling and Dungeons & Dragons. I play the trombone (jazz) and piano accordion (folk) and adore Don Ellis's [*Autumn*](https://www.youtube.com/watch?v=5t9oC765WpU&list=PLJa9-iROmUztRhNws6VyqZFvakxiWmH28).


# Footer
footer_show_references: true
references_title: References are available upon request # (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
